// <auto-generated />
using System;
using Assigment_2_Task.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assigment_2_Task.Migrations
{
    [DbContext(typeof(PersonDBContext))]
    [Migration("20220224162917_SeedingDB")]
    partial class SeedingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assigment_2_Task.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("54bddba9-2373-45a9-b382-c2892a764bbd"),
                            BirthPlace = "Hải Dương",
                            DateOfBirth = new DateTime(2000, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Tân",
                            Gender = 0,
                            LastName = "Lều Duy"
                        },
                        new
                        {
                            Id = new Guid("db8b1c0b-8327-4b8a-9792-c839abcff892"),
                            BirthPlace = "Hải Dương",
                            DateOfBirth = new DateTime(1996, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            Gender = 1,
                            LastName = "John"
                        },
                        new
                        {
                            Id = new Guid("d3db22a3-affb-441c-929a-9a326c3a5243"),
                            BirthPlace = "Hải Dương",
                            DateOfBirth = new DateTime(1967, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alan",
                            Gender = 2,
                            LastName = "Ưalker"
                        },
                        new
                        {
                            Id = new Guid("43258efb-e780-4cc6-a3c2-01f7dd112500"),
                            BirthPlace = "Hải Dương",
                            DateOfBirth = new DateTime(1796, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Man",
                            Gender = 0,
                            LastName = "IRON"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
