// <auto-generated />
using System;
using Assignment_3_Product.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_3_Product.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220225075722_IntialDatabaseAndSeeding")]
    partial class IntialDatabaseAndSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Assignment_3_Product.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3399eb3-acd5-430e-b38a-d5993d01f03c"),
                            Name = "Đồ điện"
                        },
                        new
                        {
                            Id = new Guid("f05250dc-8ba4-473d-96ed-39a632c69423"),
                            Name = "Đồ cơ khí"
                        },
                        new
                        {
                            Id = new Guid("19abfb80-c933-4377-9de8-5f430c11fc01"),
                            Name = "Đồ gia dụng"
                        });
                });

            modelBuilder.Entity("Assignment_3_Product.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("71161bdf-bab5-4204-91be-537dde7a6384"),
                            CategoryId = new Guid("b3399eb3-acd5-430e-b38a-d5993d01f03c"),
                            Manufacture = "Hàn Quốc",
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = new Guid("28f0d0cb-6ff8-4a99-a732-d7c7829a5b3d"),
                            CategoryId = new Guid("b3399eb3-acd5-430e-b38a-d5993d01f03c"),
                            Manufacture = "Trung Quốc",
                            Name = "Tivi"
                        },
                        new
                        {
                            Id = new Guid("8bf64e1c-d538-409f-a0ad-2a7035956388"),
                            CategoryId = new Guid("f05250dc-8ba4-473d-96ed-39a632c69423"),
                            Manufacture = "Việt Nam",
                            Name = "Máy đục"
                        },
                        new
                        {
                            Id = new Guid("bf188a93-c640-46b6-8408-3e3d35235ce4"),
                            CategoryId = new Guid("f05250dc-8ba4-473d-96ed-39a632c69423"),
                            Manufacture = "Mỹ",
                            Name = "Máy khoan"
                        },
                        new
                        {
                            Id = new Guid("501ceb80-773d-4909-a7ed-363bd79cf439"),
                            CategoryId = new Guid("19abfb80-c933-4377-9de8-5f430c11fc01"),
                            Manufacture = "Úc",
                            Name = "Bếp từ"
                        },
                        new
                        {
                            Id = new Guid("9f67dd5f-1cbd-49c3-9b01-64c40c5109fd"),
                            CategoryId = new Guid("19abfb80-c933-4377-9de8-5f430c11fc01"),
                            Manufacture = "Nga",
                            Name = "Nồi cơm"
                        },
                        new
                        {
                            Id = new Guid("0bc6b6cd-afeb-4994-890a-f3e0fbe0b499"),
                            CategoryId = new Guid("19abfb80-c933-4377-9de8-5f430c11fc01"),
                            Manufacture = "Campuchia",
                            Name = "Máy giặt"
                        },
                        new
                        {
                            Id = new Guid("7f1d94f3-5fca-40d3-b5bd-d1e08337b1d0"),
                            CategoryId = new Guid("19abfb80-c933-4377-9de8-5f430c11fc01"),
                            Manufacture = "Hàn Quốc",
                            Name = "Bàn Là"
                        });
                });

            modelBuilder.Entity("Assignment_3_Product.Models.Product", b =>
                {
                    b.HasOne("Assignment_3_Product.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Assignment_3_Product.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
